ip link add VRF1 type vrf table 1001
ip link add VRF2 type vrf table 1002
ip link add link eth1 name eth1.10 type vlan id 10
ip link add link eth1 name eth1.20 type vlan id 20

ip link set eth1.10 up
ip link set eth1.20 up
ip link set eth1.10 master VRF1
ip link set eth1.20 master VRF2

ip addr add 10.10.10.10/24 dev eth1.10
ip addr add 20.20.20.20/24 dev eth1.20

ip link set VRF1 up
ip link set VRF2 up

ip route add default via 10.10.10.1 dev eth1.10 table 1001
ip route add default via 20.20.20.1 dev eth1.20 table 1002
