!Command: show running-config
!Running configuration last done at: Tue Sep 15 16:51:32 2026
!Time: Tue Sep 15 17:18:58 2026

version 10.5(2) Bios:version  
hostname LEAF1
vdc LEAF1 id 1
  limit-resource vlan minimum 16 maximum 4094
  limit-resource vrf minimum 2 maximum 4096
  limit-resource port-channel minimum 0 maximum 511
  limit-resource m4route-mem minimum 58 maximum 58
  limit-resource m6route-mem minimum 8 maximum 8

feature telnet
feature nxapi
feature scp-server
nv overlay evpn
feature bgp
feature netconf
feature grpc
feature interface-vlan
feature vn-segment-vlan-based
feature bfd
feature nv overlay

no password strength-check
username admin password 5 $5$AMMMOK$/UPgOfyKcqD18iw50MBjo6mhBGEr6JuUBAgOAQOJ70.  role network-admin
ssh key rsa 2048 
ip domain-lookup
copp profile strict
snmp-server user admin network-admin auth md5 376267D202AF40FF91C622B0EC772C199B18 priv aes-128 365A38DE5AF340A694E66080F97D21488357 localizedV2key
rmon event 1 log trap public description FATAL(1) owner PMON@FATAL
rmon event 2 log trap public description CRITICAL(2) owner PMON@CRITICAL
rmon event 3 log trap public description ERROR(3) owner PMON@ERROR
rmon event 4 log trap public description WARNING(4) owner PMON@WARNING
rmon event 5 log trap public description INFORMATION(5) owner PMON@INFO

vlan 1,10,20
vlan 10
  name VLAN10
  vn-segment 10010
vlan 20
  name VLAN20
  vn-segment 10020

route-map RM_REDISTRIBUTE-Lo0 permit 10
  match interface loopback0 
vrf context management
  ip route 0.0.0.0/0 10.0.0.2
  ipv6 route 0::/0 2001:db8::1


interface Vlan1

interface nve1
  no shutdown
  host-reachability protocol bgp
  source-interface loopback0
  member vni 10010
    ingress-replication protocol bgp
  member vni 10020
    ingress-replication protocol bgp

interface Ethernet1/1
  description P2P-SPINE1
  no switchport
  mtu 9214
  bfd interval 100 min_rx 100 multiplier 3
  ip address 10.1.2.1/31
  no shutdown

interface Ethernet1/2
  description P2P-SPINE2
  no switchport
  mtu 9214
  bfd interval 100 min_rx 100 multiplier 3
  ip address 10.1.2.7/31
  no shutdown

interface Ethernet1/3
  description SRV1
  switchport mode trunk
  switchport trunk allowed vlan 10,20
  spanning-tree port type edge

interface mgmt0
  vrf member management
  ip address 10.0.0.15/24
  ipv6 address 2001:db8::2/64

interface loopback0
  description ROUTER-ID-VTEP
  ip address 10.1.0.3/32
icam monitor scale

line console
line vty
router bgp 65001
  router-id 10.1.0.3
  address-family ipv4 unicast
    redistribute direct route-map RM_REDISTRIBUTE-Lo0
    maximum-paths 4
  address-family l2vpn evpn
    maximum-paths 4
  neighbor 10.1.0.1
    remote-as 65000
    update-source loopback0
    ebgp-multihop 5
    address-family l2vpn evpn
      send-community
      send-community extended
  neighbor 10.1.0.2
    remote-as 65000
    update-source loopback0
    ebgp-multihop 5
    address-family l2vpn evpn
      send-community
      send-community extended
  neighbor 10.1.2.0
    bfd
    remote-as 65000
    address-family ipv4 unicast
  neighbor 10.1.2.6
    bfd
    remote-as 65000
    address-family ipv4 unicast
evpn
  vni 10010 l2
    rd 10.1.0.3:10010
    route-target import 10010:10010
    route-target export 10010:10010
  vni 10020 l2
    rd 10.1.0.3:10020
    route-target import 10020:10020
    route-target export 10020:10020
