! Command: show running-config
! device: FW (vEOS-lab, EOS-4.29.2F)
!
! boot system flash:/vEOS-lab.swi
!
no aaa root
!
alias srb show running-config section bgp
!
transceiver qsfp default-mode 4x10G
!
service routing protocols model multi-agent
!
hostname FW
!
spanning-tree mode mstp
!
vlan 110
   name TR-FW-TENANT1
!
vlan 120
   name TR-FW-TENANT2
!
interface Ethernet1
   description TRUNK-2-BLEAF
   switchport trunk allowed vlan 110,120
   switchport mode trunk
!
interface Ethernet2
!
interface Ethernet3
!
interface Ethernet4
!
interface Ethernet5
!
interface Ethernet6
!
interface Ethernet7
!
interface Ethernet8
!
interface Loopback0
   description ROUTER-ID
   ip address 10.1.0.7/32
!
interface Loopback1
   description 8.8.8.8
   ip address 8.8.8.8/32
!
interface Management1
!
interface Vlan110
   description TR-FW-TENANT1
   ip address 10.1.2.17/31
!
interface Vlan120
   description TR-FW-TENANT2
   ip address 10.1.2.19/31
!
ip routing
!
router bgp 65500
   router-id 10.1.0.7
   maximum-paths 4 ecmp 4
   neighbor BORDER peer group
   neighbor BORDER remote-as 65004
   neighbor BORDER bfd
   neighbor 10.1.2.16 peer group BORDER
   neighbor 10.1.2.18 peer group BORDER
   !
   address-family ipv4
      neighbor BORDER activate
      neighbor BORDER default-originate always
!
end
